//Register
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "fumine",
    "password": "2212"
}

###

//Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "fumine",
    "password": "2212"
}

###

//Get Posts
GET http://localhost:5000/api/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzNmOGZkYzZhMTJiMjEzMjBiNGRhYmQiLCJpYXQiOjE2NjUxMDk5OTF9.6pIAPE3w0Vk8vQ37drcjFng-TCrJ0ipiEskHz0vY1oU

###

//Create Posts
POST http://localhost:5000/api/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzNmOGZkYzZhMTJiMjEzMjBiNGRhYmQiLCJpYXQiOjE2NjUxMDk5OTF9.6pIAPE3w0Vk8vQ37drcjFng-TCrJ0ipiEskHz0vY1oU

{
    "title": "Book",
    "description": "Reading",
    "url": "google.com",
    "author": "Eddie",
    "chapter": 3,
    "status": "CONTINUE",
    "likeCount": 0
}

###

//Update Posts

PUT http://localhost:5000/api/post/633f901b6a12b21320b4dac1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzNmOGZkYzZhMTJiMjEzMjBiNGRhYmQiLCJpYXQiOjE2NjUxMDk5OTF9.6pIAPE3w0Vk8vQ37drcjFng-TCrJ0ipiEskHz0vY1oU

{
    "title": "Manga",
    "description": "Watching",
    "url": "google.com",
    "author": "Eddie",
    "chapter": 5,
    "status": "CONTINUE",
    "likeCount": 7
}

###

//Delete Posts

DELETE http://localhost:5000/api/post/633f901b6a12b21320b4dac1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzNmOGZkYzZhMTJiMjEzMjBiNGRhYmQiLCJpYXQiOjE2NjUxMDk5OTF9.6pIAPE3w0Vk8vQ37drcjFng-TCrJ0ipiEskHz0vY1oU